# Generated by Django 5.2.1 on 2025-06-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('factura', 'Factura comercial'), ('lista_embalaje', 'Lista de embalaje'), ('iva', 'Declaración de IVA'), ('aviso_embarque', 'Aviso de embarque')], max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ruta_archivo', models.FileField(upload_to='documentos_pdfs/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('valido', 'Válido'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10)),
                ('observacionDocumento', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
